
import React, { useState } from 'react';

interface CodeTerminalProps {
  code: string;
}

export const CodeTerminal: React.FC<CodeTerminalProps> = ({ code }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRunOnDune = () => {
    // Copy code first
    navigator.clipboard.writeText(code);
    setCopied(true);
    // Open Dune New Query
    window.open('https://dune.com/queries/new', '_blank');
  };

  return (
    <div className="w-full mt-6 bg-[#0a0a0a] border border-gray-800 rounded-lg overflow-hidden font-mono text-xs md:text-sm shadow-2xl animate-in fade-in slide-in-from-bottom duration-1000">
       
       {/* Terminal Header */}
       <div className="flex justify-between items-center px-4 py-2 bg-[#111] border-b border-gray-800">
          <div className="flex items-center gap-2">
             <div className="flex gap-1.5">
               <div className="w-2.5 h-2.5 rounded-full bg-red-500/20 border border-red-500/50"></div>
               <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/20 border border-yellow-500/50"></div>
               <div className="w-2.5 h-2.5 rounded-full bg-green-500/20 border border-green-500/50"></div>
             </div>
             <span className="text-gray-500 ml-2 text-[10px] uppercase">generated_query.sql</span>
          </div>
          
          <div className="flex gap-2">
            <button 
                onClick={handleCopy} 
                className={`text-[10px] px-3 py-1 rounded transition-all border
                    ${copied ? 'bg-green-900/30 text-green-400 border-green-500/30' : 'bg-gray-800 text-gray-400 hover:text-white border-gray-700'}
                `}
            >
                {copied ? 'COPIED' : 'COPY'}
            </button>
            <button 
                onClick={handleRunOnDune} 
                className="text-[10px] px-3 py-1 rounded transition-all bg-orange-600/20 text-orange-400 border border-orange-500/40 hover:bg-orange-600/40 hover:text-orange-200 flex items-center gap-1 font-bold"
            >
                RUN ON DUNE ↗
            </button>
          </div>
       </div>

       {/* Code Content */}
       <div className="p-4 overflow-x-auto bg-[#0a0a0a] relative group">
          <pre className="text-gray-300 font-mono text-[11px] md:text-xs leading-relaxed whitespace-pre-wrap break-all selection:bg-orange-900 selection:text-white">
            <span className="text-purple-400">-- Generated by Bu Ke Qi Oracle for Monad / Dune V2</span>
            {'\n'}
            {code}
          </pre>
          
          {/* Subtle overlay */}
          <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/5 pointer-events-none"></div>
       </div>
    </div>
  );
};
